Dark mode
New-BaseGroup/FrontEnd pull request #13
Opened 2022-09-26 07:12 UTC by AhmadALshalabi

2022-09-26 16:38 UTC, Omar-Slik approved these changes

2022-09-26 21:09 UTC, A-Lord commented on src/components/UI/SideBar.vue
> -		link: '/balance',
Här vill du skriva över omars nya balanc med income och expense

2022-09-26 21:18 UTC, A-Lord commented on src/components/UI/SideBar.vue
> +  <div class="flex flex-row relative">
Varför har du lagt till relative på sidebaren och varför är det fixed bottom-0 på ThemeToggle .  Det dom gör nu är att förstöra sidan design när man förminskar eller förstorar fönstret med sidan. 
![reactive](https://user-images.githubusercontent.com/90420563/192382372-cae106a8-94f2-43b7-a414-c0d74297b651.png)
![reactive2](https://user-images.githubusercontent.com/90420563/192382375-5e5cc6dd-a9d3-4d31-97d9-0a71efde75ac.png)

2022-09-26 21:30 UTC, A-Lord commented on src/assets/tailwind.css
> +    @apply absolute top-1/2 left-[100%] mb-auto px-1 py-5  my-auto rounded-r-full hover:text-white hover:bg-[#3094a1] border-[#3094a1] bg-white  text-[#3094a1] border active:scale-110;
Här säger du att sidebarknappen ska få gå in och använda sig av maincontents space. med din absolute tag.
![absolute](https://user-images.githubusercontent.com/90420563/192383960-54f83f88-676f-4153-85c9-77f25e7a8b1b.png)

Så här ser det ut i dev just nu,. då håller sig sidebar + knapp bara inom sin flex row. och main content har sin egen flex row . 
![noAboslutPosition](https://user-images.githubusercontent.com/90420563/192383963-8efcf02d-aa42-4295-9372-0ce57ffd5415.png)

2022-09-26 21:49 UTC, AhmadALshalabi commented on src/components/UI/SideBar.vue
> -		link: '/balance',
fixat, rebase funkat inte som man tror

2022-09-26 21:51 UTC, A-Lord requested changes
När du lägger till relative/absolute position måste du se till att sidans design fortfarande funkar reactivt.  Jag rekomederar dock att vara sparsamm med dom då dom inte funkar någe vidare tillsammans med flexbox och grid.    Ta en titt på https://ishadeed.com/article/less-absolute-positioning-modern-css/ t.ex.

2022-09-27 00:25 UTC, A-Lord approved these changes
Ser awesome ut! . flyttade så classen som bestämmer om det är dark eller light nu är tvingad till 100% av allt content eller mins hela skärmen så det inte blir så här. 
![scrollbug](https://user-images.githubusercontent.com/90420563/192403941-93fff4a7-4341-472f-8278-aa52c01c475e.png)

2022-09-27 05:44 UTC, KimNordstrom approved these changes

2022-09-27 07:18 UTC, merged